qlib_init:
  provider_uri: ./data/input/qlib_data
  region: cn
  exp_manager:
    class: MLflowExpManager
    module_path: qlib.workflow.expm
    kwargs:
      uri: "file:./data/results_qrun"
      default_exp_name: "qlib_experiment"

market: &market csi300
benchmark: &benchmark sh000300

data_handler_config: &data_handler_config
    start_time: 2024-12-19
    end_time: 2025-11-24
    fit_start_time: 2024-12-19
    fit_end_time: 2025-06-13
    instruments: *market

port_analysis_config: &port_analysis_config
  strategy:
    class: SoftTopkStrategy
    module_path: qlib.contrib.strategy.cost_control
    kwargs:
        topk: 5
        trade_impact_limit: 0.1
        risk_degree: 0.95
        signal: <PRED>

  backtest:
    start_time: 2025-06-16
    end_time: 2025-11-24
    account: 100000000
    benchmark: *benchmark
    exchange_kwargs:
        limit_threshold: 0.095
        deal_price: close
        open_cost: 0.0005
        close_cost: 0.0015
        min_cost: 5

task:
  model:
    class: LGBModel
    module_path: qlib.contrib.model.gbdt
    kwargs:
        loss: mse
        max_depth: 2
        num_leaves: 4
        num_threads: 1

  dataset:
    class: DatasetH
    module_path: qlib.data.dataset
    kwargs:
        handler:
          class: DataHandlerLP
          module_path: qlib.data.dataset.handler
          kwargs: 
            instruments: *market
            start_time: 2024-12-19
            end_time: 2025-11-24
            data_loader:
              class: QlibDataLoader
              module_path: qlib.data.dataset.loader
              kwargs:
                config:
                    feature:
                        - ["$close", "$volume", "$alpha_001", "$alpha_002", "$alpha_003", "$alpha_004", "$alpha_005", "$alpha_006", "$alpha_007", "$alpha_008", "$alpha_009", "$alpha_010"]
                        - ["close", "volume", "alpha_001", "alpha_002", "alpha_003", "alpha_004", "alpha_005", "alpha_006", "alpha_007", "alpha_008", "alpha_009", "alpha_010"]
                    label:
                        - ["Ref($close, -2)/Ref($close, -1) - 1"]
                        - ["LABEL"]


        segments:
            train: [2024-12-19, 2025-06-13]
            valid: [2024-12-19, 2025-06-13]
            test: [2025-06-16, 2025-11-24]

  record:
    - class: SignalRecord
      module_path: qlib.workflow.record_temp
      kwargs: {}
    - class: PortAnaRecord
      module_path: qlib.workflow.record_temp
      kwargs:
          config: *port_analysis_config
