# todo：这是一个非常好的文件。我建议你详细展开说说这个配置文件的优劣。
#优点：开箱即用，无需手动处理数据、模型训练、回测等流程，工作量较小。
#缺点：灵活性较低，自定义化弱，如果采用复杂的交易策略，需要手动配置；输出存在临时文件和日志，需要手动清理，并需要将pkl文件转换为csv文件。

#Qlib 的 系统配置 ，告诉 Qlib 从当前目录找 自定义模块
sys:
  rel_path:
    - ./

#初始化部分
qlib_init:
  provider_uri: ./data/input/qlib_data
  region: cn
  exp_manager:
    class: MLflowExpManager
    module_path: qlib.workflow.expm
    kwargs:
      uri: "file:./data/results_qrun"
      default_exp_name: "qlib_experiment"
#基准配置
benchmark: &benchmark SH600000
#时间与股票集
data_handler_config: &data_handler_config
    start_time: 2024-12-19
    end_time: 2025-11-25
    fit_start_time: 2024-12-19
    fit_end_time: 2025-06-13
    instruments:
      market: csi300
      filter_pipe: []
#定义回测策略（回测策略需要自己写一个py文件）
port_analysis_config: &port_analysis_config
  strategy:
    class: ScoreWeightedStrategy
    module_path: workflow_qrun
    kwargs:
        signal: <PRED>
        topk: 20
        cash_reserve: 0.05
        normalize_method: "minmax"
#执行回测，定义回测参数
  backtest:
    start_time: 2025-06-16
    end_time: 2025-11-24
    account: 100000000
    benchmark: *benchmark
    exchange_kwargs:
        deal_price: close
        open_cost: 0.00005
        close_cost: 0.00015
        min_cost: 5
#  定义模型参数
task:
  model:
    class: LGBModel
    module_path: qlib.contrib.model.gbdt
    kwargs:
        loss: mse
        early_stopping_rounds: 50
        num_boost_round: 300
        learning_rate: 0.05
        num_leaves: 16
        max_depth: 4
        num_threads: 1
#定义数据集生成参数并划分训练集和测试集
  dataset:
    class: DatasetH
    module_path: qlib.data.dataset
    kwargs:
        handler:
          class: DataHandlerLP
          module_path: qlib.data.dataset.handler
          kwargs:
            instruments:
              market: csi300
              filter_pipe: []
            start_time: 2024-12-19
            end_time: 2025-11-25
            infer_processors:
              - class: Fillna
                kwargs:
                  fields_group: feature
            learn_processors:
              - class: DropnaLabel
                kwargs: {}
            data_loader:
              class: QlibDataLoader
              module_path: qlib.data.dataset.loader
              kwargs:
                config:
                    feature:
                        - ["$close", "$volume", "$alpha_001", "$alpha_002", "$alpha_003", "$alpha_004", "$alpha_005", "$alpha_006", "$alpha_007", "$alpha_008", "$alpha_009", "$alpha_010"]
                        - ["close", "volume", "alpha_001", "alpha_002", "alpha_003", "alpha_004", "alpha_005", "alpha_006", "alpha_007", "alpha_008", "alpha_009", "alpha_010"]
                    label:
                        - ["Ref($close, -2)/Ref($close, -1) - 1"]
                        - ["LABEL"]


        segments:
            train: [2024-12-19, 2025-06-13]
            valid: [2024-12-19, 2025-06-13]
            test: [2025-06-16, 2025-11-24]
#打印输出结果
  record:
    - class: SignalRecord
      module_path: qlib.workflow.record_temp
      kwargs: {}
    - class: PortAnaRecord
      module_path: qlib.workflow.record_temp
      kwargs:
          config: *port_analysis_config
